name: Build and test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: env BAZEL_CXXOPTS=-std=c++14 bazel build -k //...
      - run: env BAZEL_CXXOPTS=-std=c++14 bazel test -k //... --test_tag_filters=-noci
  build-and-test-cmake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run : |
          set -eux
          
          CPUS=$(grep -c ^processor /proc/cpuinfo)
          
          mkdir ${GITHUB_WORKSPACE}/build && cd ${GITHUB_WORKSPACE}/build
          cmake -DCMAKE_BUILD_TYPE=Release -DOpenCensus_BUILD_TESTING=ON -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/install ..
          make -j ${CPUS}
          make install

      - name: Test
        run: |
          set -eux
          CPUS=$(grep -c ^processor /proc/cpuinfo)
          cd ${GITHUB_WORKSPACE}/build
          make test -j ${CPUS}
